<!doctype html>
<html lang="en">
    <head>
        <title>PHP Within an HTML File</title>
    </head>
    <body>
        <?php
            echo "<p>hello from an HTML file</p>";
        ?>
        <p>
            The above line should be generated by PHP.
        </p>
    </body>
</html>